#!/bin/sh
# build-videos.sh — regenerate the web copies of the FACTS lesson videos.
#
# Source (untouched, gitignored, ~2.6 GB — FACTS 2020–2026 teacher materials):
#   archive/facts-originals/…      ← camera exports, 1080p @ ~17 Mbps
# Output (committed, AUTO-GENERATED — do not edit by hand):
#   facts/videos/<id>.mp4               ← 720p H.264 CRF 27 (≤850k), AAC 96k mono, faststart
#   facts/videos/<id>.jpg               ← poster frame
#   facts/videos/videos.js              ← durations, read by facts.js
#
# Why the originals are so heavy: they were saved at the camera's
# recording bitrate (~17 Mbps). A 2–3 minute clip at that rate is
# ~300 MB. For a lesson video watched on a phone, 720p at ~1 Mbps
# looks the same and is ~15× smaller.
#
# The id → source map below must match `id`/`origin` in facts-data.js.
# Run from the repo root:  sh facts/build-videos.sh
set -e
SRC="archive/facts-originals"
OUT="facts/videos"
mkdir -p "$OUT"

build() { # $1 = id, $2 = source path, $3 = poster second
  if [ -f "$OUT/$1.mp4" ] && [ "$OUT/$1.mp4" -nt "$SRC/$2" ]; then
    echo "skip $1 (up to date)"; return
  fi
  echo "build $1 ← $2"
  ffmpeg -v error -y -i "$SRC/$2" \
    -vf "scale=-2:720" -c:v libx264 -preset slow -crf 27 -maxrate 850k -bufsize 1700k -profile:v high -pix_fmt yuv420p \
    -c:a aac -b:a 96k -ac 1 -movflags +faststart "$OUT/$1.mp4"
  ffmpeg -v error -y -ss "$3" -i "$OUT/$1.mp4" -frames:v 1 -vf "scale=-2:360" -q:v 4 "$OUT/$1.jpg"
}

build unpack-and-pack       "videos/video_03.mp4"                                   60
build check-at-home         "videos/04_check-dan-tranh_at-home_01.mp4"              60
build tuning                "Lesson Materials/Week 3 11-2-2020/10_tuning.mp4"       40
build mother-ocean-vibrato  "Lesson Materials/Mother Ocean/Mother-Ocean_sung-n-vibratos_01.mp4" 40
build mother-ocean-sung-2   "Lesson Materials/Mother Ocean/Mother-Ocean_sung-n-vibratos_02.mp4" 40
build mother-ocean-chords   "Lesson Materials/Mother Ocean/Mother-Ocean_chords-and-vibratos_01.mp4" 40
build mother-ocean-octave   "Lesson Materials/Mother Ocean/Mother-Ocean_Octave_and_vibratos.mp4" 40

# One Mother, A Hundred Children — teacher play-alongs (FACTS 2020-21)
build one-mother-a          "one-mother/One-Mother_A-Hundred-Children_Melody-Section-A.mp4" 30
build one-mother-b          "one-mother/One-Mother-A-Hundred-Children_Melody_Section-B.mp4" 30
build one-mother-aab        "one-mother/One Mother A Hundred Children Melody Sections A-A-B.mp4" 30
build one-mother-rhythm     "one-mother/One-Mother-A-Hundred-Children_Rhythm.mp4" 30
build one-mother-whole      "one-mother/One Mother Melody Rhythm Intro AAB Outro.mp4" 30

# Tablature techniques — short clips with the tab symbol on screen (Nov 2020)
build tech-glide-1          "techniques/Tab Dan Tranh _ Glide 1.mov" 3
build tech-glide-2          "techniques/Tab Dan Tranh _ Glide 2.mov" 3
build tech-play-after-bend  "techniques/Tab Dan Tranh _ Play after Bend.mov" 2
build tech-play-then-bend   "techniques/Tab Dan Tranh _ Play then Bend.mov" 2
build tech-vibration        "techniques/Tab Dan Tranh _ Vibration 1.mov" 2

# videos.js — durations read from the built files (derived, never hand-typed)
{
  echo "// AUTO-GENERATED by facts/build-videos.sh — do not edit."
  echo "window.FACTS_VIDEOS = {"
  for f in "$OUT"/*.mp4; do
    id=$(basename "$f" .mp4)
    d=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$f")
    echo "  \"$id\": { seconds: $d },"
  done
  echo "};"
} > "$OUT/videos.js"

# Cloudflare Pages rejects any file over 25 MiB — fail loudly here instead.
# (-maxrate 850k keeps a ~3.5 min clip near 22 MB.)
big=$(find "$OUT" -type f -size +25M)
if [ -n "$big" ]; then echo "ERROR: over Cloudflare's 25 MiB limit:"; echo "$big"; exit 1; fi

du -sh "$OUT"/*
