// facts.js — renderer for facts/index.html.
//
// Data-agnostic: reads window.FACTS (facts-data.js),
// window.FACTS_VIDEOS (videos/videos.js, AUTO-GENERATED by
// build-videos.sh) and window.PHOTO_META (../photos-meta.js).
// Never put dates, titles, links or prose in here.
//
// Audience: FACTS students in Philadelphia — the page is in English.
// Vietnamese appears only as real names of things, explained in the
// glossary (FACTS.glossary).
//
// Two registries:
//   MATERIAL_KINDS — how a material (video / app / page / read) is linked
//   BLOCK_KINDS    — how a content block (p, list, checklist, …) is drawn
// To support something new, add a registry entry first, then use it in
// facts-data.js.
//
// Derived, never stored: session numbers, the next class, the selected day, the showcase
// countdown, the year strip, video durations, which sessions use a video.

(function () {
  const F = window.FACTS;
  const VIDEOS = window.FACTS_VIDEOS || {};
  const PHOTO_META = window.PHOTO_META || {};
  const SITE = "../"; // this page lives one level below the site root

  // ---------- tiny DOM helpers ----------
  function build(el, attrs, kids) {
    for (const [k, v] of Object.entries(attrs || {})) {
      if (v == null || v === false) continue;
      if (k === "class") el.setAttribute("class", v);
      else if (k === "text") el.textContent = v;
      else el.setAttribute(k, v);
    }
    for (const kid of kids.flat(Infinity)) {
      if (kid == null || kid === false) continue;
      el.appendChild(typeof kid === "string" ? document.createTextNode(kid) : kid);
    }
    return el;
  }
  const h = (tag, attrs, ...kids) => build(document.createElement(tag), attrs, kids);
  const svgEl = (tag, attrs, ...kids) => build(document.createElementNS("http://www.w3.org/2000/svg", tag), attrs, kids);

  // ---------- per-viewer storage (stays on this device) ----------
  function loadSet(key) {
    try { return new Set(JSON.parse(localStorage.getItem(key) || "[]")); } catch (e) { return new Set(); }
  }
  function saveSet(key, set) {
    try { localStorage.setItem(key, JSON.stringify([...set])); } catch (e) { /* private mode: fine */ }
  }

  // ---------- dates (ISO strings, local calendar days) ----------
  const parse = (iso) => { const [y, m, d] = iso.split("-").map(Number); return new Date(y, m - 1, d); };
  const pad = (n) => String(n).padStart(2, "0");
  const isoOf = (dt) => `${dt.getFullYear()}-${pad(dt.getMonth() + 1)}-${pad(dt.getDate())}`;
  const TODAY = isoOf(new Date());
  const daysBetween = (a, b) => Math.round((parse(b) - parse(a)) / 86400000);
  const MON = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const DOW = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  const DOW_LONG = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const dateShort = (iso) => { const d = parse(iso); return `${DOW[d.getDay()]}, ${MON[d.getMonth()]} ${d.getDate()}`; };
  const dateLong = (iso) => { const d = parse(iso); return `${DOW_LONG[d.getDay()]}, ${MON[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`; };

  // ---------- derive sessions, timeline ----------
  const C = F.calendar;
  const sessions = C.dates.map((date, i) => ({ n: i + 1, date }));
  const sessionByDate = Object.fromEntries(sessions.map((s) => [s.date, s]));
  const eventsByDate = {};
  for (const e of F.events) (eventsByDate[e.date] = eventsByDate[e.date] || []).push(e);
  const materialById = Object.fromEntries(F.materials.map((m) => [m.id, m]));
  const materialsOf = (n) => (F.plan[n] || []).map((id) => materialById[id]).filter(Boolean);
  const showcase = F.events.find((e) => e.kind === "showcase");
  const timeline = [...new Set([...C.dates, ...C.closures, ...Object.keys(eventsByDate)])].sort();
  const next = sessions.find((s) => s.date >= TODAY) || null;

  // ---------- validation: the data must match its sources ----------
  const problems = [];
  if (C.expectedCount && C.dates.length !== C.expectedCount)
    problems.push(`${C.dates.length} class dates, source says ${C.expectedCount}`);
  for (const d of [...C.dates, ...C.closures]) if (parse(d).getDay() !== 5) problems.push(`${d} is not a Friday`);
  const refs = [...F.tools, ...F.everyClass.materials, ...Object.values(F.plan).flat(), ...F.songs.flatMap((s) => s.materials)];
  for (const id of refs) if (!materialById[id]) problems.push(`unknown material "${id}"`);
  for (const m of F.materials) if (m.kind === "read" && !F.sections.some((x) => x.id === m.section))
    problems.push(`material "${m.id}" points at missing section "${m.section}"`);
  if (problems.length) console.error("[facts] data problems:\n" + problems.join("\n"));

  // ---------- "I watched it" — one Set, one writer ----------
  // Every element that shows watched state carries data-watch="<id>";
  // paintWatched() repaints them all.
  const WATCHED_KEY = "maml_facts_2026_watched";
  const watched = loadSet(WATCHED_KEY);
  const videoIds = F.materials.filter((m) => m.kind === "video").map((m) => m.id);
  function setWatched(id, on) {
    on ? watched.add(id) : watched.delete(id);
    saveSet(WATCHED_KEY, watched);
    paintWatched();
  }
  function paintWatched() {
    for (const el of document.querySelectorAll("[data-watch]")) {
      const on = watched.has(el.dataset.watch);
      el.classList.toggle("is-watched", on);
      if (el.type === "checkbox") el.checked = on;
    }
    const done = videoIds.filter((id) => watched.has(id)).length;
    for (const el of document.querySelectorAll("[data-watch-count]")) el.textContent = `${done}/${videoIds.length}`;
  }

  // ---------- MATERIAL_KINDS ----------
  const fmtDur = (s) => `${Math.floor(s / 60)}:${pad(Math.round(s % 60))}`;
  const MATERIAL_KINDS = {
    video: { icon: "▶", href: (m) => `#v-${m.id}`, meta: (m) => (VIDEOS[m.id] ? fmtDur(VIDEOS[m.id].seconds) : "video") },
    app:   { icon: "↗", href: (m) => m.url, external: true, meta: () => "app" },
    page:  { icon: "→", href: (m) => SITE + m.path, meta: () => "guide" },
    read:  { icon: "↓", href: (m) => `#${m.section}`, meta: () => "read" },
  };
  function materialLink(m, cls) {
    const kind = MATERIAL_KINDS[m.kind];
    return h("a", {
      class: `facts-mat facts-mat--${m.kind} ${cls || ""}`,
      href: kind.href(m),
      target: kind.external ? "_blank" : null,
      rel: kind.external ? "noopener" : null,
      "data-watch": m.kind === "video" ? m.id : null,
    },
      h("span", { class: "facts-mat-icon", "aria-hidden": "true", text: kind.icon }),
      h("span", { class: "facts-mat-label", text: m.title }),
      h("span", { class: "facts-mat-meta", text: kind.meta(m) }));
  }

  // ---------- BLOCK_KINDS ----------
  const BLOCK_KINDS = {
    h3: (b) => h("h3", { class: "facts-h3", text: b.text }),
    p: (b) => [
      h("p", { class: "facts-p", text: b.text }),
      b.edit ? h("p", { class: "facts-edit", text: "✎ " + b.edit }) : null,
    ],
    list: (b) => h("ul", { class: "facts-list" }, b.items.map((t) => h("li", { text: t }))),
    steps: (b) => h("ol", { class: "facts-steps" }, b.items.map((t) => h("li", { text: t }))),
    checklist: (b) => {
      const key = `maml_facts_2026_check_${b.key}`;
      const done = loadSet(key);
      return h("ul", { class: "facts-checklist" }, b.items.map((t, i) => {
        const box = h("input", { type: "checkbox" });
        box.checked = done.has(i);
        box.addEventListener("change", () => { box.checked ? done.add(i) : done.delete(i); saveSet(key, done); });
        return h("li", {}, h("label", {}, box, t));
      }));
    },
    image: (b) => h("figure", { class: "facts-figure" }, h("img", { src: b.src, alt: b.alt, loading: "lazy" })),
    images: (b) => h("div", { class: "facts-scroll" }, h("div", { class: "facts-images" },
      b.items.map((it) => h("figure", { class: "facts-figure" },
        h("img", { src: it.src, alt: it.alt, loading: "lazy" }),
        h("figcaption", { text: it.caption }))))),
    strings: () => h("div", { class: "facts-scroll" }, h("table", { class: "facts-strings" },
      h("tr", {}, h("th", { text: "String" }), F.strings.map((_, i) => h("td", { text: String(i + 1) }))),
      h("tr", {}, h("th", { text: "Pitch" }), F.strings.map((p) => h("td", { text: p }))))),
    table: (b) => h("div", { class: "facts-scroll" }, h("table", { class: "facts-table" },
      h("tr", {}, b.head.map((t) => h("th", { text: t })), h("th", {})),
      b.rows.map((r) => h("tr", {}, r.slice(0, b.head.length).map((t) => h("td", { text: t })),
        h("td", { class: "facts-table-note", text: r[b.head.length] || "" }))))),
  };

  // ---------- blocks ----------

  // The year strip: one column per date. The top band draws the 17
  // strings running the whole width; each class column carries its
  // bridge (nhạn), stepping diagonally up like bridges on a real đàn
  // tranh. Bridges and dates share one x-axis because they are the
  // same column.
  function renderYear() {
    const root = document.getElementById("year");
    const STRINGS = 17, GAP = 7, TOP = 22, BAND = TOP + GAP * (STRINGS - 1) + 22, COL = 56;
    const N = sessions.length;
    const yOf = (n) => TOP + GAP * (STRINGS - 1) - ((n - 1) / (N - 1)) * GAP * (STRINGS - 1);
    const done = sessions.filter((x) => x.date < TODAY).length;

    const band = (children) => svgEl("svg", { class: "facts-year-band", width: COL, height: BAND, viewBox: `0 0 ${COL} ${BAND}`, "aria-hidden": "true" },
      Array.from({ length: STRINGS }, (_, k) =>
        svgEl("line", { x1: 0, x2: COL, y1: TOP + GAP * k, y2: TOP + GAP * k, class: "facts-j-string" })),
      children);

    root.appendChild(h("div", { class: "facts-year-col facts-year-head" },
      h("div", { class: "facts-year-bandlabel", style: `height:${BAND}px` },
        h("strong", { text: `${done} of ${N}` }), h("span", { text: "Fridays done" }),
        h("span", { class: "facts-year-hint", text: "one bridge = one Friday" })),
      h("div", { class: "facts-year-month" }),
      h("div", { class: "facts-year-day" }),
      h("div", { class: "facts-year-lane", text: "Session" }),
      h("div", { class: "facts-year-lane", text: "Events" })));

    let lastMonth = "";
    for (const date of timeline) {
      const d = parse(date);
      const month = date.slice(0, 7);
      const s = sessionByDate[date];
      const evs = eventsByDate[date] || [];
      const mark = evs.some((e) => e.kind === "showcase") ? "★" : evs.some((e) => e.kind === "finale") ? "♪" : null;
      const state = !s ? "off" : next && s.n === next.n ? "next" : date < TODAY ? "past" : "future";
      const scale = state === "next" ? 1.5 : 1;
      const col = h("div", {
        class: `facts-year-col is-${state} ${month !== lastMonth ? "is-month-start" : ""}`,
        role: "button",
        tabindex: "0",
        "data-date": date,
        title: s ? `Session ${s.n} · ${dateLong(date)}` : `${dateLong(date)}${C.closures.includes(date) ? " · no class" : ""}`,
      },
        band(s ? [
          svgEl("path", { class: "facts-j-bridge", d: "M-7 7 L-2.5 -8 L2.5 -8 L7 7 Z", transform: `translate(${COL / 2} ${yOf(s.n)}) scale(${scale})` }),
          mark ? svgEl("text", { x: COL / 2, y: yOf(s.n) - 14 * scale, class: "facts-j-star" }, mark) : null,
        ] : []),
        h("div", { class: "facts-year-month", text: month !== lastMonth ? `${MON[d.getMonth()]} ’${String(d.getFullYear()).slice(2)}` : "" }),
        h("div", { class: "facts-year-day" },
          h("span", { class: "facts-year-dow", text: DOW[d.getDay()] }),
          h("span", { class: "facts-year-date", text: String(d.getDate()) })),
        h("div", { class: "facts-year-lane facts-year-n", text: s ? String(s.n) : C.closures.includes(date) ? "off" : "" }),
        h("div", { class: "facts-year-lane facts-year-events" },
          evs.map((e) => h("span", { class: "facts-year-event", title: e.who || null, text: e.title }))));
      col.addEventListener("click", () => select(date, true));
      col.addEventListener("keydown", (ev) => {
        if (ev.key === "Enter" || ev.key === " ") { ev.preventDefault(); select(date, true); }
      });
      root.appendChild(col);
      lastMonth = month;
    }

  }

  // Bring the selected day into view, just right of the sticky labels.
  function scrollYearTo(date) {
    const root = document.getElementById("year");
    const target = root.querySelector(`[data-date="${date}"]`);
    const head = root.querySelector(".facts-year-head");
    if (target) root.parentElement.scrollLeft = Math.max(0, target.offsetLeft - head.offsetWidth - 2 * target.offsetWidth);
  }

  // ---------- selected day: one state, one writer ----------
  // `selected` is the date shown in the day card (default: next class).
  // select() is the only writer; it repaints the card and marks the column.
  let selected = next ? next.date : null;

  function select(date, userAction) {
    selected = date;
    renderDayCard();
    for (const el of document.querySelectorAll(".facts-year-col[data-date]"))
      el.classList.toggle("is-selected", el.dataset.date === selected);
    if (userAction) {
      // Keep the strip AND the card in view: if the card is off-screen,
      // scroll so the strip sits just under the sticky topbar.
      const r = document.getElementById("next").getBoundingClientRect();
      if (r.top < 0 || r.top > innerHeight - 160) {
        const bar = document.querySelector(".topbar");
        const barH = bar && getComputedStyle(bar).position !== "static" ? bar.offsetHeight : 0;
        const top = document.getElementById("year").getBoundingClientRect().top + scrollY - barH - 12;
        scrollTo({ top, behavior: "smooth" });
      }
    }
  }

  function relDays(date) {
    const d = daysBetween(TODAY, date);
    return d === 0 ? "Today!" : d === 1 ? "Tomorrow" : d === -1 ? "Yesterday" : d > 1 ? `In ${d} days` : `${-d} days ago`;
  }

  function renderDayCard() {
    const root = document.getElementById("next");
    root.textContent = "";
    if (problems.length) root.appendChild(h("p", { class: "facts-warn", text: "⚠ " + problems.join(" · ") }));
    if (!selected) {
      root.appendChild(h("div", { class: "facts-next" },
        h("p", { class: "facts-next-title", text: "That's a wrap — thank you for a wonderful year!" })));
      return;
    }
    const s = sessionByDate[selected];
    const isNext = next && s && s.n === next.n;
    const eyebrow = isNext ? "Next class" : s ? (selected < TODAY ? "Past class" : "Coming up")
      : C.closures.includes(selected) ? "No class" : "Event";
    const mats = s ? materialsOf(s.n) : [];
    const toShowcase = showcase ? sessions.filter((x) => x.date >= TODAY && x.date < showcase.date).length : 0;
    root.appendChild(h("div", { class: `facts-next ${isNext ? "" : "is-other"}` },
      h("div", { class: "facts-next-top" },
        h("p", { class: "facts-next-eyebrow", text: eyebrow }),
        !isNext && next ? h("button", { class: "facts-next-back", type: "button", text: "← back to next class" }) : null),
      h("p", { class: "facts-next-count", text: relDays(selected) }),
      h("p", { class: "facts-next-title",
        text: s ? `Session ${s.n} of ${sessions.length} · ${dateLong(selected)}` : dateLong(selected) }),
      (eventsByDate[selected] || []).map((e) => h("p", { class: "facts-tag facts-tag--event", text: e.who ? `${e.title} · ${e.who}` : e.title })),
      s ? h("div", { class: "facts-everyclass" },
        h("span", { text: F.everyClass.text }),
        F.everyClass.materials.map((id) => materialLink(materialById[id]))) : null,
      !s && C.closures.includes(selected) ? h("p", { class: "facts-empty", text: "No ensemble class this Friday — enjoy the break." }) : null,
      s ? (mats.length
        ? [h("p", { class: "facts-next-lead", text: selected < TODAY ? "What we used:" : "Watch before class:" }),
           h("div", { class: "facts-scroll" }, h("div", { class: "facts-mats" }, mats.map((m) => materialLink(m))))]
        : h("p", { class: "facts-empty", text: "Nothing to watch yet — just bring your picks and your ears." })) : null,
      h("div", { class: "facts-next-stats" },
        showcase && showcase.date >= TODAY
          ? h("p", { class: "facts-stat" },
              h("span", { class: "facts-stat-num", text: String(toShowcase) }),
              h("span", { text: `${toShowcase === 1 ? "Friday" : "Fridays"} until the Showcase (${dateShort(showcase.date)})` }))
          : null,
        h("p", { class: "facts-stat" },
          h("span", { class: "facts-stat-num", "data-watch-count": "" }),
          h("span", { text: "videos watched" })))));
    const back = root.querySelector(".facts-next-back");
    if (back) back.addEventListener("click", () => { select(next.date, false); scrollYearTo(next.date); });
    paintWatched();
  }

  function renderTools() {
    const root = document.getElementById("tools");
    for (const id of F.tools) {
      const m = materialById[id];
      root.appendChild(h("li", {},
        materialLink(m, "facts-tool"),
        m.hint ? h("span", { class: "facts-tool-hint", text: m.hint }) : null));
    }
  }

  function renderSessions() {
    const root = document.getElementById("sessions");
    for (const s of sessions) {
      const mats = materialsOf(s.n);
      root.appendChild(h("li", {
        id: `s-${s.n}`,
        class: ["facts-session", s.date < TODAY ? "is-past" : "", next && s.n === next.n ? "is-next" : ""].join(" "),
      },
        h("span", { class: "facts-session-n", text: String(s.n) }),
        h("button", { class: "facts-session-date", type: "button", "data-date": s.date, text: dateShort(s.date) }),
        h("span", { class: "facts-session-tags" },
          (eventsByDate[s.date] || []).map((e) => h("span", { class: "facts-tag facts-tag--event", text: e.title }))),
        h("span", { class: "facts-session-mats" },
          mats.length ? mats.map((m) => materialLink(m)) : h("span", { class: "facts-empty", text: "nothing to watch yet" }))));
    }
  }

  function wireSessionDates() {
    for (const b of document.querySelectorAll(".facts-session-date"))
      b.addEventListener("click", () => { select(b.dataset.date, true); scrollYearTo(b.dataset.date); });
  }

  function renderSongs() {
    const root = document.getElementById("songs");
    root.before(h("p", { class: "facts-songs-intro", text: F.songsIntro }));
    for (const song of F.songs) {
      root.appendChild(h("li", { id: `song-${song.id}`, class: "facts-song" },
        h("h3", { class: "facts-song-title", text: song.title }),
        h("p", { class: "facts-song-about", text: song.about }),
        song.materials.length
          ? h("div", { class: "facts-song-mats" }, song.materials.map((id) => materialLink(materialById[id])))
          : h("p", { class: "facts-empty", text: "materials coming" })));
    }
    document.getElementById("songsource").textContent = `About the songs: ${F.SOURCES.showcase2026}.`;
  }

  function renderVideos() {
    const root = document.getElementById("videos");
    const usedIn = {}; // sessions that use each video — derived from the plan
    for (const [n, ids] of Object.entries(F.plan)) for (const id of ids) (usedIn[id] = usedIn[id] || []).push(Number(n));
    for (const g of F.videoGroups) {
      const items = F.materials.filter((m) => m.kind === "video" && m.group === g.id);
      if (!items.length) continue;
      root.appendChild(h("h3", { class: "facts-h3", text: g.title }));
      root.appendChild(h("div", { class: "facts-scroll" }, h("ol", { class: "facts-videos" }, items.map((m) => {
        const src = `videos/${m.id}.mp4`;
        const used = (usedIn[m.id] || []).sort((a, b) => a - b);
        const video = h("video", { controls: "", preload: "none", playsinline: "", poster: `videos/${m.id}.jpg`, src });
        video.addEventListener("ended", () => setWatched(m.id, true));
        const box = h("input", { type: "checkbox", "data-watch": m.id });
        box.addEventListener("change", () => setWatched(m.id, box.checked));
        return h("li", { id: `v-${m.id}`, class: "facts-video", "data-watch": m.id },
          video,
          h("p", { class: "facts-video-title", text: m.title }),
          h("p", { class: "facts-video-meta" },
            VIDEOS[m.id] ? fmtDur(VIDEOS[m.id].seconds) : "",
            used.map((n) => [" · ", h("a", { href: `#s-${n}`, text: `session ${n}` })])),
          h("label", { class: "facts-watched" }, box, "I watched it"));
      }))));
    }
  }

  function renderSections() {
    for (const sec of F.sections) {
      const root = document.getElementById(sec.id);
      if (!root) { console.error(`[facts] no mount for section "${sec.id}"`); continue; }
      root.appendChild(h("h2", { class: "facts-h2", text: sec.title }));
      for (const b of sec.blocks) root.appendChild(h("div", { class: "facts-block-item" }, BLOCK_KINDS[b.type](b)));
      if (sec.source) root.appendChild(h("p", { class: "facts-source", text: F.sectionSources[sec.source] }));
    }
  }

  function renderPhotos() {
    const root = document.getElementById("photos");
    for (const file of F.photos) {
      const meta = PHOTO_META[file];
      root.appendChild(h("figure", { class: "facts-photo" },
        h("img", { src: `${SITE}photos-thumb/${file}`, alt: meta ? meta.en : "", loading: "lazy" }),
        meta ? h("figcaption", { text: meta.en }) : null));
    }
  }

  function renderGlossary() {
    const root = document.getElementById("glossary");
    for (const g of F.glossary)
      root.append(h("dt", { lang: "vi", text: g.term }), h("dd", { text: g.meaning }));
  }

  function renderFooterNotes() {
    document.getElementById("thanks").textContent = "Special thanks to " + F.thanks.join(" · ");
    document.getElementById("calsource").textContent =
      `Numbers = session. Calendar source: ${F.SOURCES.contract}.`;
  }

  renderYear();
  renderTools();
  renderSessions();
  renderSongs();
  renderVideos();
  renderSections();
  renderPhotos();
  renderGlossary();
  renderFooterNotes();
  wireSessionDates();
  if (selected) { select(selected, false); scrollYearTo(selected); } else renderDayCard();
  paintWatched();
})();
